[tool.poetry]
package-mode = false

[tool.poetry.dependencies]
python = "^3.10"
opencv-python = "^4.9.0.80"
opendatasets = "^0.1.22"
matplotlib = "^3.9.0"
numpy = "^1.26.4"
networkx = "^3.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
