[tool.poetry]
package-mode = false

[tool.poetry.dependencies]
python = "^3.10"
bs4 = "^0.0.2"
requests = "^2.31.0"
opencv-python = "^4.9.0.80"
torch = "^2.2.0"
torchvision = "^0.17.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
